package:
  name: geomatics
  version: 0.6

about:
  author: Riley Hales
  description: GIS tools developed by Riley Hales for the BYU Hydroinformatics Lab
  license: BSD 3-Clause License
  license_family: BSD
  doc_url: https://geomatics.readthedocs.io
  dev_url: https://github.com/rileyhales/geomatics

build:
  string: b0
  noarch: python

source:
  path: ..

requirements:
  build:
    - python>=3
  run:
    - python>=3
    - rasterio
    - rasterstats
    - netcdf4
    - requests
    - python-dateutil
    - numpy
    - pandas
    - pyshp
    - pygrib

outputs:
  - name: geomatics

test:
  imports:
    - rasterio
    - rasterstats
    - xarray
    - netcdf4
    - dateutil

extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - rileyhales