{% set name = "geomatics" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: auto_generated_hash
#  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xarray
    - cfgrib
    - rasterio
    - rasterstats
    - netCDF4
    - requests
    - python-dateutil
    - numpy
    - pandas
    - pyshp
    - pygrib

test:
  imports:
    - geomatics

about:
  home: https://github.com/rileyhales/geomatics
  summary: Geospatial tools in pure python developed by Riley Hales as part of a Master's Thesis at Brigham Young University
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geomatics.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
